export const ACTIONS_TYPE_LIST_EMPRESA = "ACTIONS_TYPE_LIST_EMPRESA";
export const ACTIONS_TYPE_USER = "ACTIONS_TYPE_USER";
export const ACTIONS_TYPE_USERS = "ACTIONS_TYPE_USERS";
export const ACTIONS_TYPE_TOKEN_USERS = "ACTIONS_TYPE_TOKEN_USERS";
export const ACTIONS_TYPE_TIME_TOKEN_USERS = "ACTIONS_TYPE_TIME_TOKEN_USERS";